# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.17.142952'

RELEASE_GIT_HEAD = '5e6859a271a5f5ad79c37fb6bcf49f20f7af5487'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'revich2/yt-dlp'

ORIGIN = 'revich2/yt-dlp'

_pkg_version = '2024.04.17.142952'
